
## Overview of the research

In a soccer match, referees can give red cards to player for aggressive behaviour. Players that receive a red card are immediately removed from the match and can not return for the rest of the match. Although a standard set of rules and guidelines exists, a referee's decision on red cards is inherently a judgment call. 

We hypothesize that soccer players with darker skin tone would receive more red cards as expectancy in social perception may play a role in the referees' decision making. 

### Data

To test the hypothesis, Silberzahn et al. (2018)  collected data on all soccer players who played in the first male divisions of four different national leagues in the 2012-2013 season plus data on their interaction with all referees across their professional careers. The collected data contains multiple seasons for most players. They also collected ratings on the darkness of the skin tones from two independent raters that provided ratings based on available photos. The full data set is available on their project page at https://osf.io/gvm2z/. Silberzahn et al. (2018) collected the data in June 2014. 

For the scope of this exercise, we will look at a subset of the original data consisting of 75 players each from the English and German leagues with the following variables<sup>2</sup>. 

#### Player attributes

+   `player`: player name
+   `playerShort`: short player ID; this variable is a unique identifier for each player
+   `birthday`: player's birthday in _dd.mm.yyyy_ format
+   `height`: player's height in cm
+   `weight`: player's weight in kg (as of June 2014)
+   `position`: player's typical position (as of June 2014)
+   `club`: player's team (as of June 2014)
+   `leagueCountry`: player's league (as of June 2014)
+   `rater1`: 5-point scale rating on player's skin tone by rater 1 (0 - very light skin; 5 -very dark skin)
+   `rater2`: 5-point scale rating on player's skin tone by rater 2 (0 - very light skin; 5 -very dark skin)

#### Referee attribute

+   `refNum`: anonymized unique referee ID 

#### Player-referee interaction attributes

+   `games`: total number of games where the player played with the referee officiating
+   `redCards`: total number of red cards given by the referee to the player
+   `yellowCards`: total number of yellow cards given by the referee to the player
+   `goals`: total number of goals the player scored in matches where the referee officiated
+   `victories`: total number of games the player's team won where the referee officiated
+   `defeats`: total number of games the player's team lost where the referee officiated

Each row of the data corresponds to a unique player-referee pair. The data is available in `soccer` object throughout the exercise. It contains `r format(nrow(soccer), big.mark = ",")` rows for `r format(n_distinct(soccer$playerShort), big.mark = ",")` players and `r format(n_distinct(soccer$refNum), big.mark = ",")` referees.

```{r data, exercise=TRUE}
# you can check what the data looks like
head(soccer)
```

In the following section, we will use the data to fit a simple binomial logistic regression model using the count variables for red cards and games.

```{=html}
<hr />
<footnote id="note2"><sup>2</sup>The details on how we prepared the subset are available in <a href="https://raw.githubusercontent.com/mjmoon/sta490-soccer/main/soccer.log" target="_blank">this log file</a> and <a href="https://raw.githubusercontent.com/mjmoon/sta490-soccer/main/prepdata.R" target="_blank">this script</a>.</footnote>
```
