## Worksheet

In this section, you will expand the multiverse analysis from the previous section and conduct the analysis on your own. We are interested in answering the question on whether soccer referees give more red cards to dark-skinned players. Suppose you decided to answer the questions by investigating the logistic model as defined below:

$$\text{logit} E(Y_{i,j,k}) = \beta X_i, \text{ where}$$
$Y_{i,j,k}$ is 1 if player $i$ receives a red card in game $k$ officiated by referee $j$ and $X_i$ represents a vector containing player $i$'s mean skin tone rating and covariates plus the interaction term. 

> At the end of the exercise, you will print the worksheet and submit a PDF file as described in *Submission instruction* at the bottom of this page.

### Multiverse setup

Suppose you are interested in all combinations of the following options. 

A.  Player's position (`position`): Consider the options discussed in _Multiverse analysis in R_ section:  
__A1.__ not including the position variable;  
__A2.__ grouping positions into fielders vs. goal keepers;  
__A3.__ grouping positions into 4 groups of forwards vs. midfielders vs. defenders vs. goal keepers; and  
__A4.__ including the position variable as is.
B.  League country<sup><a href="#note5">5</a></sup> (`leagueCountry`): The data set includes players playing in English and German leagues. It is possible that the variable is a confounder as a league may tend to give out more red cards and have more or less players with darker skin tones. On the other hand, some argue that the variable is unreliable because players move between the leagues and the data set doesn't capture the movements. Consider the following options:  
__B1.__ not including the league country variable; and  
__B2.__ using the league country variable.
C.  Player size<sup><a href="#note5">5</a></sup> (`height` or `weight`): Players that are larger may be more willing to engage in physical contacts with other players due to their physical advantage. This may lead to more red cards to larger players. You can control for a player's size using either their height or weight. Consider the options of:  
__C1.__ using the height variable to represent a player's size; and  
__C2.__ using the weight variable to represent a player's size.

### Code your own multiverse

Conduct the multiverse analysis using and answer the questions on Quercus quiz. [The starter code](www/starter.R) includes the codes for installing necessary libraries and and loading the data set.

```{=html}
<hr />
<footnote id="note5"><sup><a href="#note5">5</a></sup>Some of the rationales for using or not using these variables by the analysts participating in the crowdsoucring study (Silberzahn et al., 2018) are available among the study's <a href="https://osf.io/un3e5/" target="_blank">supplementary information</a>.</footnote>
```